Repository lightninglabs/taproot-assets, pull requests merged in 2023-07, with the labels that each got.

#388 rpc: fix AssetWallet REST API endpoints not found
  rpcserver.go
Labels: v0.2.3, P2

#393 QueryAssetStats and UniverseStats no auth client access
  perms/perms.go
Labels: v0.2.3

#389 Add block height to asset mint proof
  itest/assertions.go
  proof/append.go
  proof/mint.go
  proof/proof.go
  proof/proof_test.go
  proof/records.go
  rpcserver.go
  tapdb/assets_store.go
  tapdb/sqlc/assets.sql.go
  tapdb/sqlc/migrations/000002_assets.up.sql
  tapdb/sqlc/models.go
  tapgarden/caretaker.go
  taprpc/taprootassets.pb.go
  taprpc/taprootassets.proto
  taprpc/taprootassets.swagger.json
  taprpc/universerpc/universe.swagger.json
Labels: v0.2.3

#396 Improve universe stats
  cmd/tapcli/universe.go
  go.mod
  itest/addrs_test.go
  itest/assertions.go
  itest/collectible_split_test.go
  itest/full_value_split_test.go
  itest/mint_batch_stress_test.go
  itest/multi_asset_group_test.go
  itest/psbt_test.go
  itest/re-issuance_test.go
  itest/round_trip_send_test.go
  itest/send_test.go
  itest/universe_test.go
  perms/perms.go
  proof/verifier.go
  rpcserver.go
  tapcfg/server.go
  tapdb/addrs.go
  tapdb/asset_minting.go
  tapdb/assets_common.go
  tapdb/interfaces.go
  tapdb/postgres.go
  tapdb/sqlc/db_custom.go
  tapdb/sqlc/migrations/000002_assets.up.sql
  tapdb/sqlc/migrations/000008_universe_events_timestamp.down.sql
  tapdb/sqlc/migrations/000008_universe_events_timestamp.up.sql
  tapdb/sqlc/models.go
  tapdb/sqlc/querier.go
  tapdb/sqlc/queries/universe.sql
  tapdb/sqlc/universe.sql.go
  tapdb/sqlite.go
  tapdb/universe.go
  tapdb/universe_stats.go
  tapdb/universe_stats_test.go
  tapdb/universe_test.go
  tapgarden/interface.go
  taprpc/universerpc/universe.pb.go
  taprpc/universerpc/universe.pb.gw.go
  taprpc/universerpc/universe.pb.json.go
  taprpc/universerpc/universe.proto
  taprpc/universerpc/universe.swagger.json
  taprpc/universerpc/universe.yaml
  taprpc/universerpc/universe_grpc.pb.go
  universe/interface.go
Labels: universe, v0.2.3

#400 Add proof block height verification
  chain_bridge.go
  itest/assertions.go
  proof/mock.go
  proof/proof_test.go
  proof/verifier.go
  tapfreighter/chain_porter.go
  tapgarden/caretaker.go
  tapgarden/interface.go
  tapgarden/mock.go
Labels: v0.2.3

#408 rpcserver: add missing merkle root and tapscript sibling fields to DecodeProof RPC
  itest/assertions.go
  rpcserver.go
Labels: v0.2.3

#346 Preliminary refactor in preparation for adding multiverse support
  tapdb/universe.go
  tapdb/universe_forest.go
  tapdb/universe_test.go
Labels: v0.3
