Repository lightninglabs/taproot-assets, pull requests merged in 2023-10, with the labels that each got.

#525 decoding: fix panics by limiting max decode sizes in proofs, commitments and assets
  Makefile
  address/address.go
  address/address_test.go
  asset/asset.go
  asset/encoding.go
  commitment/encoding.go
  commitment/proof.go
  itest/assertions.go
  itest/assets_test.go
  make/fuzz_flags.mk
  proof/encoding.go
  proof/file.go
  proof/meta.go
  proof/meta_test.go
  proof/proof.go
  proof/records.go
  proof/taproot.go
  proof/testdata/fuzz/FuzzProof/bd3d7cb5ef5fb7a4
  proof/tx.go
  rpcserver.go
  scripts/fuzz.sh
  taprpc/mintrpc/mint.swagger.json
  taprpc/taprootassets.pb.go
  taprpc/taprootassets.proto
  taprpc/taprootassets.swagger.json
Labels: v0.3

#558 loadtest: add multi send test
  itest/loadtest/config.go
  itest/loadtest/load_test.go
  itest/loadtest/mint_batch_test.go
  itest/loadtest/send_test.go
  itest/loadtest/utils.go
Labels: testing

#555 tapfreighter+tapgarden: prevent fee overpayment
  tapfreighter/wallet.go
  tapgarden/caretaker.go
Labels: bug fix, fees

#612 universe: make additional details optional to speed up query
  cmd/tapcli/universe.go
  rpcserver.go
  tapdb/multiverse.go
  tapdb/universe_test.go
  taprpc/universerpc/universe.pb.go
  taprpc/universerpc/universe.pb.gw.go
  taprpc/universerpc/universe.proto
  taprpc/universerpc/universe.swagger.json
  universe/base.go
  universe/interface.go
  universe/syncer.go
  universe_rpc_diff.go
Labels: enhancement
