Repository lightninglabs/taproot-assets, pull requests merged in 2023-09, with the labels that each got.

#449 tapdb: allow batch inserting proofs when syncing universe, remove write lock for RegisterIssuance
  .github/workflows/main.yaml
  Makefile
  fn/recv.go
  fn/recv_test.go
  itest/mint_batch_stress_test.go
  itest/tapd_harness.go
  make/testing_flags.mk
  rpcserver.go
  tapcfg/config.go
  tapcfg/server.go
  tapdb/interfaces.go
  tapdb/interfaces_test.go
  tapdb/multiverse.go
  tapdb/postgres.go
  tapdb/universe.go
  tapdb/universe_stats.go
  tapdb/universe_test.go
  tapgarden/caretaker.go
  tapgarden/planter.go
  universe/auto_syncer.go
  universe/base.go
  universe/interface.go
  universe/syncer.go
Labels: database, v0.3

#488 proof: add magic bytes to individual proofs and proof files
  cmd/tapcli/proofs.go
  itest/addrs_test.go
  itest/assertions.go
  itest/send_test.go
  proof/file.go
  proof/proof.go
  proof/proof_test.go
  proof/testdata/ownership-proof.hex
  proof/testdata/proof-file.hex
  proof/testdata/proof.hex
  proof/testdata/proof_tlv_encoding_generated.json
  proof/testdata/proof_tlv_encoding_regtest.json
  rpcserver.go
  taprpc/assetwalletrpc/assetwallet.swagger.json
  taprpc/taprootassets.pb.go
  taprpc/taprootassets.proto
  taprpc/taprootassets.swagger.json
  taprpc/universerpc/universe.pb.go
  taprpc/universerpc/universe.proto
  taprpc/universerpc/universe.swagger.json
Labels: proofs, burning

#485 Implement sorting functionality and add total_supply for Universe Ass…
  rpcserver.go
  tapdb/sqlc/queries/universe.sql
  tapdb/sqlc/universe.sql.go
  tapdb/universe_stats.go
  tapdb/universe_stats_test.go
  taprpc/universerpc/universe.pb.go
  taprpc/universerpc/universe.proto
  taprpc/universerpc/universe.swagger.json
  universe/interface.go
Labels: universe

#492 CLI: Improve minting user experience
  cmd/tapcli/assets.go
  itest/assertions.go
  itest/assets_test.go
  itest/re-org_test.go
  itest/universe_test.go
  rpcserver.go
  tapdb/multiverse.go
  tapdb/sqlc/queries/universe.sql
  tapdb/sqlc/universe.sql.go
  tapgarden/batch.go
  tapgarden/caretaker.go
  tapgarden/interface.go
  tapgarden/planter.go
  tapgarden/planter_test.go
  tapgarden/seedling.go
  taprpc/mintrpc/mint.pb.go
  taprpc/mintrpc/mint.proto
  taprpc/mintrpc/mint.swagger.json
  taprpc/mintrpc/mint_grpc.pb.go
  taprpc/universerpc/universe.pb.go
  taprpc/universerpc/universe.proto
  taprpc/universerpc/universe.swagger.json
  universe/interface.go
Labels: minting, batching, bug fix

#505 mssmt: fuzz test for CompressedProof
  mssmt/fuzz_test.go
Labels: fuzzing

#504 proof: fuzz test for File and Proof
  proof/fuzz_test.go
Labels: fuzzing

#496 Generalise multiverse method names to support all proofs.
  config.go
  itest/tapd_harness.go
  tapcfg/server.go
  tapdb/multiverse.go
  tapdb/universe_test.go
  universe/base.go
  universe/interface.go
Labels: proofs, multiverse
