Repository lightninglabs/taproot-assets, pull requests merged in 2024-08, with the labels that each got.

#1041 tapchannel: check for feature bits before opening chans
  feature_bit_verifier.go
  go.mod
  go.sum
  tapcfg/server.go
  tapchannel/aux_funding_controller.go
Labels: bug fix, tap-channels, validation

#1048 [custom channels]: add new RPC methods for asset channel specific calls
  go.mod
  go.sum
  itest/channels_test.go
  itest/tapd_harness.go
  itest/test_list_on_test.go
  perms/perms.go
  rfq/manager.go
  rpcserver.go
  taprpc/Dockerfile
  taprpc/gen_protos.sh
  taprpc/gen_protos_docker.sh
  taprpc/tapchannelrpc/tapchannel.pb.go
  taprpc/tapchannelrpc/tapchannel.pb.gw.go
  taprpc/tapchannelrpc/tapchannel.proto
  taprpc/tapchannelrpc/tapchannel.swagger.json
  taprpc/tapchannelrpc/tapchannel.yaml
  taprpc/tapchannelrpc/tapchannel_grpc.pb.go
  taprpc/tapchannelrpc/taprootassetchannels.pb.json.go
Labels: gRPC, tap-channels, aux invoice

#1076 rfq: actually set subject asset in QueryRateTick
  rfq/oracle.go
  rfq/oracle_test.go
Labels: bug fix, rfq

#1074 Spend transaction change outputs even if undelivered proof(s)
  itest/send_test.go
  itest/test_list_on_test.go
  rpcserver.go
  tapdb/assets_store.go
  tapdb/assets_store_test.go
  tapdb/sqlc/querier.go
  tapdb/sqlc/queries/transfers.sql
  tapdb/sqlc/transfers.sql.go
  tapfreighter/chain_porter.go
  tapfreighter/interface.go
  tapfreighter/parcel.go
  taprpc/assetwalletrpc/assetwallet.swagger.json
  taprpc/marshal.go
  taprpc/taprootassets.pb.go
  taprpc/taprootassets.proto
  taprpc/taprootassets.swagger.json
Labels: proofs

#1037 TLV encoding: add forward-compatibility
  address/address.go
  address/address_test.go
  address/mock.go
  address/records.go
  address/testdata/address_tlv_encoding_generated.json
  asset/asset.go
  asset/asset_test.go
  asset/mock.go
  asset/records.go
  asset/records_test.go
  asset/testdata/asset_tlv_encoding_generated.json
  commitment/commitment_test.go
  commitment/encoding.go
  commitment/mock.go
  commitment/proof.go
  commitment/records.go
  internal/test/generic.go
  itest/addrs_test.go
  itest/test_list_on_test.go
  proof/meta.go
  proof/meta_test.go
  proof/mock.go
  proof/proof.go
  proof/proof_test.go
  proof/records.go
  proof/taproot.go
  proof/taproot_test.go
  proof/testdata/proof_tlv_encoding_generated.json
  tappsbt/testdata/psbt_encoding_generated.json
  vm/testdata/vm_validation_generated.json
  vm/testdata/vm_validation_generated_error_cases.json
Labels: tlv, proofs, assets

#1077 Add challenge to proof ownership flows
  address/address.go
  address/address_test.go
  itest/ownership_test.go
  itest/test_list_on_test.go
  proof/verifier.go
  rpcserver.go
  tapchannel/aux_funding_controller.go
  tapfreighter/wallet.go
  tappsbt/create.go
  taprpc/assetwalletrpc/assetwallet.pb.go
  taprpc/assetwalletrpc/assetwallet.proto
  taprpc/assetwalletrpc/assetwallet.swagger.json
Labels: verification, proofs

#1103 commitment: splits shouldn't inherit locktime from inputs
  asset/asset.go
  asset/asset_test.go
  commitment/commitment_test.go
  commitment/split.go
  proof/courier.go
  proof/verifier.go
  tapfreighter/wallet.go
Labels: bug fix

#1110 Server logging cleanup
  server.go
Labels: logging

#1100 Enhance Proof Delivery Resilience with ParSliceErrCollect in ChainPorter
  fn/concurrency.go
  fn/func.go
  tapfreighter/chain_porter.go
Labels: proofs, transfers
