Repository lightninglabs/taproot-assets, pull requests merged in 2025-09, with the labels that each got.

#1739 docs/debug-handbook: create new debug run books for developers to help pattern match common issues and knowledge
  docs/debug-handbook/README.md
  docs/debug-handbook/psbt-finalization-failures.md
  docs/debug-handbook/psbt-quick-reference.md
Labels: documentation, debugging

#1759 docs: add generated and reviewed developer deep-dive docs
  docs/developer-deep-dive.md
  docs/developer-transaction-flow.md
  docs/hardware-wallet-support.md
  docs/taproot-asset-channels.md
  docs/taproot-asset-channels/litd-hooks.png
  docs/taproot-asset-channels/tap-channel-funding.png
  docs/taproot-asset-channels/tap-channel-payment.drawio
  docs/taproot-asset-channels/tap-channel-payment.png
  docs/taproot-asset-channels/taproot-asset-channels.png
  docs/taproot-asset-channels/taproot-chans-to-local.png
  tapgarden/README.md
Labels: documentation, no-changelog

#1784 supplyverifier: store and verify non-issuer supply pre-commitments
  docs/release-notes/release-notes-0.7.0.md
  tapdb/asset_minting.go
  tapdb/asset_minting_test.go
  tapdb/assets_common.go
  tapdb/burn_tree.go
  tapdb/migrations.go
  tapdb/multiverse.go
  tapdb/sqlc/assets.sql.go
  tapdb/sqlc/migrations/000046_supply_pre_commit_tables.down.sql
  tapdb/sqlc/migrations/000046_supply_pre_commit_tables.up.sql
  tapdb/sqlc/models.go
  tapdb/sqlc/querier.go
  tapdb/sqlc/queries/assets.sql
  tapdb/sqlc/queries/supply_commit.sql
  tapdb/sqlc/schemas/generated_schema.sql
  tapdb/sqlc/supply_commit.sql.go
  tapdb/supply_commit.go
  tapdb/supply_commit_test.go
  tapdb/supply_tree.go
  tapdb/universe.go
  universe/supplycommit/env.go
  universe/supplycommit/mock.go
  universe/supplycommit/state_machine_test.go
  universe/supplycommit/transitions.go
  universe/supplyverifier/env.go
  universe/supplyverifier/verifier.go
Labels: database, supply commit

#1803 scripts: add darioanongba signing key
  scripts/keys/darioanongba.asc
Labels: no-changelog

#1823 Add support for fetching latest supply commitment via new locator type
  cmd/commands/universe.go
  docs/release-notes/release-notes-0.7.0.md
  itest/rpcassert/universerpc.go
  itest/supply_commit_test.go
  rpcserver.go
  tapdb/supply_commit.go
  tapdb/supply_commit_test.go
  taprpc/universerpc/universe.pb.go
  taprpc/universerpc/universe.proto
  taprpc/universerpc/universe.swagger.json
  universe/supplyverifier/manager.go
Labels: gRPC, ux, supply commit

#1828 itest: fix address receives test: timestamp in the future
  tapdb/addrs.go
Labels: itests, no-changelog

#1820 Extract supply pre-commits from mint leaves during supply verifier sync
  docs/release-notes/release-notes-0.7.0.md
  itest/supply_commit_test.go
  tapdb/supply_commit.go
  tapdb/universe.go
  tapdb/universe_test.go
  universe/supplycommit/env.go
  universe/supplycommit/mock.go
  universe/supplycommit/state_machine_test.go
  universe/supplyverifier/manager.go
  universe/supplyverifier/mock.go
  universe/supplyverifier/transitions.go
  universe/supplyverifier/util.go
  universe/supplyverifier/util_test.go
  universe/supplyverifier/verifier.go
Labels: supply commit

#1783 docs: add docs that detail the asset chan funding process
  docs/asset-channel-funding.md
Labels: documentation, tap-channels

#1787 docs: add docs on e2e RFQ arch
  docs/rfq_architecture.md
Labels: documentation, no-changelog
