Repository lightninglabs/taproot-assets, pull requests merged in 2025-01, with the labels that each got.

#1269 Improve logging
  fn/option.go
  rfq/negotiator.go
  server.go
  tapchannel/aux_funding_controller.go
  universe/auto_syncer.go
Labels: logging

#1291 GitHub: update tapd's CI litd branch to testing target
  .github/workflows/main.yaml
Labels: itests, CI, lightning-terminal

#1272 Part 1: Asset Minting with V1 Asset Group Key and Chantools Cold Storage Support
  .gitignore
  Makefile
  asset/asset.go
  asset/asset_test.go
  asset/mock.go
  cmd/tapcli/assets.go
  commitment/commitment_test.go
  docs/external-group-key.md
  itest/chantools_harness.go
  itest/mint_fund_seal_test.go
  itest/test_list_on_test.go
  itest/utils.go
  proof/mint.go
  rpcserver.go
  tapdb/addrs.go
  tapdb/asset_minting_test.go
  tapdb/assets_common.go
  tapdb/assets_store_test.go
  tapdb/migrations.go
  tapdb/sqlc/assets.sql.go
  tapdb/sqlc/migrations/000026_asset_group_version_customsubtree.down.sql
  tapdb/sqlc/migrations/000026_asset_group_version_customsubtree.up.sql
  tapdb/sqlc/models.go
  tapdb/sqlc/queries/assets.sql
  tapgarden/interface.go
  tapgarden/planter.go
  tapgarden/planter_test.go
  tapgarden/seedling.go
  taprpc/marshal.go
  taprpc/mintrpc/mint.pb.go
  taprpc/mintrpc/mint.proto
  taprpc/mintrpc/mint.swagger.json
  taprpc/taprootassets.pb.go
  taprpc/taprootassets.proto
Labels: wallet, psbt, group_key

#1284 Add unit test for method ExternalKey.PubKey
  asset/asset_test.go
Labels: testing, unit-test

#1290 multi: add new v2 version of GKR based on Pedersen commitments
  asset/asset.go
  asset/group_key_reveal_test.go
  asset/testdata/rapid/TestGroupKeyRevealEncodeDecodeRapid/TestGroupKeyRevealEncodeDecodeRapid-20250113154507-29836.fail
  internal/pedersen/commitment.go
  internal/pedersen/commitment_test.go
  internal/pedersen/testdata/rapid/TestPedersenCommitmentProperties/TestPedersenCommitmentProperties-20250110122316-67631.fail
  internal/pedersen/testdata/rapid/TestPedersenCommitmentProperties_binding/TestPedersenCommitmentProperties_binding-20250110124128-45790.fail
  internal/pedersen/testdata/rapid/TestPedersenCommitmentProperties_correctness/TestPedersenCommitmentProperties_correctness-20250110123534-19936.fail
  internal/pedersen/testdata/rapid/TestPedersenCommitmentProperties_uniqueness/TestPedersenCommitmentProperties_uniqueness-20250110124128-45790.fail
  proof/proof_test.go
  tapgarden/planter.go
  tapgarden/planter_test.go
  tapscript/script.go
Labels: crypto, signing, group_key

#1308 Add Logging to Diagnose Flaky CI PostgreSQL Integration Test
  itest/assertions.go
Labels: postgres, CI

#1295 SealBatch RPC endpoint accepts signed group PSBT
  cmd/tapcli/assets.go
  docs/external-group-key.md
  itest/utils.go
  rpcserver.go
  tapgarden/planter.go
  taprpc/mintrpc/mint.pb.go
  taprpc/mintrpc/mint.proto
  taprpc/mintrpc/mint.swagger.json
Labels: optimization

#1311 PoC: CLI parsing for itest tapd harness queries
  cmd/commands/addrs.go
  cmd/commands/assets.go
  cmd/commands/cmd_profile.go
  cmd/commands/commands.go
  cmd/commands/conn.go
  cmd/commands/events.go
  cmd/commands/macaroon_jar.go
  cmd/commands/macaroon_jar_test.go
  cmd/commands/profile.go
  cmd/commands/proofs.go
  cmd/commands/rfq.go
  cmd/commands/tapdevrpc_active.go
  cmd/commands/tapdevrpc_default.go
  cmd/commands/universe.go
  cmd/tapcli/commands.go
  cmd/tapcli/main.go
  itest/integration_test.go
  itest/tapd_harness.go
Labels: itests, cli

#1299 Invoice Acceptor: ensure asset ID match between RFQ and HTLC
  asset/asset.go
  tapchannel/aux_invoice_manager.go
  tapchannel/aux_invoice_manager_test.go
Labels: security, htlc

#1324 Cleanup Asset Minting Code in Preparation for Universe Commitments
  rpcserver.go
  tapgarden/batch.go
  tapgarden/caretaker.go
  tapgarden/planter.go
  tapgarden/planter_test.go
Labels: minting, code health

#1323 Consolidate RPC Client Interfaces
  cmd/commands/commands.go
  cmd/commands/conn.go
  itest/assertions.go
  itest/interface.go
  itest/loadtest/utils.go
  itest/mint_batch_stress_test.go
  itest/multisig.go
  itest/universe_pagination_test.go
  itest/utils.go
  taprpc/utils.go
Labels: gRPC, itests, code health, cli
